
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 1qaz!QAZ
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
logging:
  file:
    name: proj_common.log